POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
  "email": "user2@gmail.com",
  "password": "My@Password123",
  "photos": [
    {
      "url": "avata/photo2.png"
    },
    {
      "url": "avata/photo3.png"
    }
  ]
}
###
